let mySprite2 = Render.getRenderSpriteVariable()
mySprite2 = sprites.create(img`
    .................
    .................
    .................
    .................
    .................
    ...ad............
    ..affdd..........
    ..affffaa........
    ..aadfffdad......
    ...faddffdf......
    ....e1adffff.....
    ....aaaffffa.....
    .....fffdffae....
    ......fafdda1e...
    .....eeeaff11e...
    .....e11ee1111e..
    .....e111e1111e..
    ......e1111111e..
    .......e111111e..
    .......e1111111e.
    .........e11111e.
    .........e11111ee
    `, SpriteKind.Player)
scene.cameraFollowSprite(mySprite2)
tiles.setCurrentTilemap(tilemap`level1`)
Render.move(mySprite2, 90, 1000)
scene.cameraShake(4, 500)
